data:
  val:
    dataset:
      module: src.data.facescape.FacescapeDataSet
      kwargs:
        root: /cluster/scratch/tguillou/facescape
        range_vert: 30
        range_hor: 45
        slide_range: 40
        depth_type: merge
        # depth_fname: depth_mesh.png
    dataloader:
      kwargs:
        shuffle: False
        batch_size: 1
        num_workers: 1