logger:
  kwargs:
    save_dir: "outputs/facescape"
    version: "NOVEL_MLP"

data:
  train:
    dataset:
      module: src.data.facescape_novel.FacescapeDataSet
      kwargs:
        root: /cluster/scratch/tguillou/facescape
        range_vert: 30
        range_hor: 45
        slide_range: 40
        slide_step: 20
    dataloader:
      kwargs:
        shuffle: true
        batch_size: 2
        num_workers: 4

  val:
    dataset:
      module: src.data.facescape_novel.FacescapeDataSet
      kwargs:
        root: /cluster/scratch/tguillou/facescape
        range_vert: 30
        range_hor: 45
        slide_range: 40
    dataloader:
      kwargs:
        shuffle: false
        batch_size: 2
        num_workers: 4

nerf:
  module: src.models.novel_pixelnerf.PixelNeRF
  kwargs:
    encoder_conf:
      module: src.models.image_encoder.SpatialEncoder
      kwargs:
        image_padding: 64
        padding_pe: 4
    poscode_conf:
      kwargs:
        num_freqs: 6
        freq_factor: 6.28
        include_input: true
    mlp_fine_conf:
      module: src.models.resnetfc.ResnetFC
      kwargs:
        n_blocks: 5
        d_hidden: 512
        combine_layer: 3
        combine_type: average

renderer:
  module: src.models.nerf_novel_renderer.NeRFRendererDGS
  kwargs:
    n_samples: 40
    n_depth_candidates: 1000
    n_gaussian: 15


optimizer_diner:
  kwargs:
    w_vgg: 0.1
    w_antibias: 5.
    ray_batch_size: 128
    img_log_interval: 10000
    lr: 1e-4

trainer:
  # ckpt_path: /cluster/home/tguillou/diner/outputs/facescape/DINER/epoch=13-step=239999.ckpt
  kwargs:
    enable_checkpointing: True
    accelerator: gpu # delete if gpus
    #  gpus:
    devices:
      - 0
    val_check_interval: 30000
    log_every_n_steps: 1000
    strategy: ddp
    limit_val_batches: 10
    check_val_every_n_epoch: null
    max_epochs: -1

checkpointing:
  kwargs:
    every_n_train_steps: 10000
    save_last: False
    save_top_k: 1